(defaults
	(object-extension ".o")
	(archive yes))

(template c
	(source-file "module.c")
	(command "$(CC) $(CFLAGS) -c $< -o $@"))

(template cpp
	(source-file "module.cpp")
	(command "$(CXX) $(CXXFLAGS) -c $< -o $@")
	(linker-flags "-lstdc++"))

(template rust
	(source-file "module.rs")
	(command "rustc --crate-type staticlib --emit obj -C panic=abort -C opt-level=2 -C overflow-checks=off $< -o $@")
    (linker-flags "-lstdc++ -lm"))
	(archive no))
